services:
    mathieubon:
        build: .
        container_name: mathieubon-website
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mathieubon.rule=Host(`mathieubon.com`)"
            - "traefik.http.routers.mathieubon.entrypoints=websecure"
            - "traefik.http.routers.mathieubon.tls.certresolver=myresolver"
        networks:
            - web

networks:
    web:
        external: true
        name: traefik_default
